/**
 * Builtin Provider Presets: 国内头部自研大模型（DeepSeek, SiliconFlow, Moonshot, Zhipu, MiniMax）
 */

import type { ProviderPreset } from "~/lib/provider-presets/types"

export const DOMESTIC_PRIMARY_PRESETS: Array<ProviderPreset> = [
  {
    id: "deepseek",
    name: "DeepSeek (深度求索)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.deepseek.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.deepseek.com/api_keys",
    description: "DeepSeek V3 / R1 推理系列",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-chat",
        upstreamId: "deepseek-chat",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-reasoner",
        upstreamId: "deepseek-reasoner",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "deepseek-anthropic",
    name: "DeepSeek (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.deepseek.com/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.deepseek.com/api_keys",
    description: "DeepSeek Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-chat",
        upstreamId: "deepseek-chat",
        endpoints: ["messages"],
      },
      {
        publicId: "deepseek-reasoner",
        upstreamId: "deepseek-reasoner",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "siliconflow",
    name: "SiliconFlow (硅基流动)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.siliconflow.cn/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://cloud.siliconflow.cn/account/ak",
    description: "全托管 Qwen3、GLM、DeepSeek 开源高并发推理",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        upstreamId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        endpoints: ["chat"],
      },
      {
        publicId: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        upstreamId: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        endpoints: ["chat"],
      },
      {
        publicId: "Qwen/Qwen3-30B-A3B-Thinking-2507",
        upstreamId: "Qwen/Qwen3-30B-A3B-Thinking-2507",
        endpoints: ["chat"],
      },
      {
        publicId: "zai-org/GLM-4.6",
        upstreamId: "zai-org/GLM-4.6",
        endpoints: ["chat"],
      },
      {
        publicId: "zai-org/GLM-4.5",
        upstreamId: "zai-org/GLM-4.5",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-ai/DeepSeek-V3",
        upstreamId: "deepseek-ai/DeepSeek-V3",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-ai/DeepSeek-R1",
        upstreamId: "deepseek-ai/DeepSeek-R1",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "moonshot",
    name: "Moonshot (月之暗面 / Kimi)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.moonshot.cn/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.moonshot.cn/console/api-keys",
    description: "Kimi K2 / 长上下文与深度思考推理模型",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "kimi-k2-thinking",
        upstreamId: "kimi-k2-thinking",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-k2-0905-preview",
        upstreamId: "kimi-k2-0905-preview",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-k2-turbo-preview",
        upstreamId: "kimi-k2-turbo-preview",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-latest",
        upstreamId: "kimi-latest",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "moonshot-anthropic",
    name: "Moonshot (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.moonshot.cn/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.moonshot.cn/console/api-keys",
    description: "Moonshot Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "kimi-k2-thinking",
        upstreamId: "kimi-k2-thinking",
        endpoints: ["messages"],
      },
      {
        publicId: "kimi-k2-0905-preview",
        upstreamId: "kimi-k2-0905-preview",
        endpoints: ["messages"],
      },
      {
        publicId: "kimi-k2-turbo-preview",
        upstreamId: "kimi-k2-turbo-preview",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "moonshot-coding",
    name: "Kimi Coding",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.kimi.com/coding",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.moonshot.cn",
    description: "Kimi 专为编程优化的 Anthropic 兼容端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "kimi-k2-thinking",
        upstreamId: "kimi-k2-thinking",
        endpoints: ["messages"],
      },
      {
        publicId: "kimi-k2-0905-preview",
        upstreamId: "kimi-k2-0905-preview",
        endpoints: ["messages"],
      },
      {
        publicId: "kimi-k2-turbo-preview",
        upstreamId: "kimi-k2-turbo-preview",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "zhipu",
    name: "Zhipu AI (智谱 GLM)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    authMode: "bearer",
    keyPlaceholder: "xxxxxxxx.yyyyyyyy",
    portalUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    description: "智谱 GLM-5.2 / GLM-5 / GLM-4.7 系列大模型",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "glm-5.2",
        upstreamId: "glm-5.2",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5",
        upstreamId: "glm-5",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5-turbo",
        upstreamId: "glm-5-turbo",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-4.7",
        upstreamId: "glm-4.7",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-4.5-air",
        upstreamId: "glm-4.5-air",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "zhipu-anthropic",
    name: "Zhipu AI (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "xxxxxxxx.yyyyyyyy",
    portalUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    description: "智谱 GLM Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "glm-5.2",
        upstreamId: "glm-5.2",
        endpoints: ["messages"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["messages"],
      },
      {
        publicId: "glm-5",
        upstreamId: "glm-5",
        endpoints: ["messages"],
      },
      {
        publicId: "glm-4.7",
        upstreamId: "glm-4.7",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "zai",
    name: "Z.AI (智谱海外)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.z.ai/api/paas/v4",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://z.ai",
    description: "Z.AI GLM-5 / GLM-4.7 系列海外服务端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "glm-5.2",
        upstreamId: "glm-5.2",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5",
        upstreamId: "glm-5",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-4.7",
        upstreamId: "glm-4.7",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "zai-anthropic",
    name: "Z.AI (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.z.ai/api/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://z.ai",
    description: "Z.AI Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "glm-5.2",
        upstreamId: "glm-5.2",
        endpoints: ["messages"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["messages"],
      },
      {
        publicId: "glm-4.7",
        upstreamId: "glm-4.7",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax (名之梦)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.minimaxi.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl:
      "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    description: "MiniMax M3 / M2.7 / Text-01 文本与多模态大模型",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "MiniMax-M3",
        upstreamId: "MiniMax-M3",
        endpoints: ["chat"],
      },
      {
        publicId: "MiniMax-M2.7",
        upstreamId: "MiniMax-M2.7",
        endpoints: ["chat"],
      },
      {
        publicId: "MiniMax-M2.7-highspeed",
        upstreamId: "MiniMax-M2.7-highspeed",
        endpoints: ["chat"],
      },
      {
        publicId: "MiniMax-Text-01",
        upstreamId: "MiniMax-Text-01",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "minimax-anthropic",
    name: "MiniMax (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.minimaxi.com/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://platform.minimaxi.com",
    description: "MiniMax Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "MiniMax-M3",
        upstreamId: "MiniMax-M3",
        endpoints: ["messages"],
      },
      {
        publicId: "MiniMax-M2.7",
        upstreamId: "MiniMax-M2.7",
        endpoints: ["messages"],
      },
      {
        publicId: "MiniMax-Text-01",
        upstreamId: "MiniMax-Text-01",
        endpoints: ["messages"],
      },
    ],
  },
]
