import { describe, expect, test } from "bun:test"

import type { OAuthAccount } from "~/lib/legacy-accounts"

import {
  getOAuthAccountSubtitle,
  isAutoGeneratedOAuthLabel,
} from "~/services/oauth/account-label"

function createOAuthAccount(
  overrides: Partial<OAuthAccount> = {},
): OAuthAccount {
  return {
    id: "test-id",
    label: "xai-1",
    provider: "xai",
    enabled: true,
    priority: 0,
    quotaState: "unknown",
    createdAt: Date.now(),
    credentials: {},
    settings: {},
    runtimeState: { authStatus: "ready" },
    ...overrides,
  }
}

describe("oauth account label helpers", () => {
  test("detects auto-generated provider labels", () => {
    expect(isAutoGeneratedOAuthLabel("xai-7", "xai")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("antigravity-8", "antigravity")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("user@example.com", "xai")).toBe(false)
    expect(isAutoGeneratedOAuthLabel("custom-name", "xai")).toBe(false)
  })

  // Phase 3.4:inferOAuthAccountLabel / upgradeOAuthAccountLabelIfNeeded 已删除
  // (无生产调用方,被 connection 原生版本 inferOAuthConnectionLabel 等替代)。

  test("returns subtitle when different from label", () => {
    const account = createOAuthAccount({
      label: "My Account",
      credentials: { email: "user@example.com" },
    })
    expect(getOAuthAccountSubtitle(account)).toBe("user@example.com")
  })
})
