import { describe, expect, test } from "bun:test"

import type { OAuthAccount } from "~/lib/accounts"

import {
  getOAuthAccountSubtitle,
  inferOAuthAccountLabel,
  isAutoGeneratedOAuthLabel,
  upgradeOAuthAccountLabelIfNeeded,
} from "~/services/oauth/account-label"

function createOAuthAccount(
  overrides: Partial<OAuthAccount> = {},
): OAuthAccount {
  return {
    id: "test-id",
    label: "xai-1",
    provider: "xai",
    enabled: true,
    priority: 0,
    quotaState: "unknown",
    createdAt: Date.now(),
    credentials: {},
    settings: {},
    runtimeState: { authStatus: "ready" },
    ...overrides,
  }
}

describe("oauth account label helpers", () => {
  test("detects auto-generated provider labels", () => {
    expect(isAutoGeneratedOAuthLabel("xai-7", "xai")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("antigravity-8", "antigravity")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("user@example.com", "xai")).toBe(false)
    expect(isAutoGeneratedOAuthLabel("custom-name", "xai")).toBe(false)
  })

  test("infers label from OAuth credentials", () => {
    const account = createOAuthAccount({
      credentials: { email: "user@example.com" },
    })
    expect(inferOAuthAccountLabel(account)).toBe("user@example.com")
  })

  test("upgrades auto-generated labels after OAuth login", () => {
    const account = createOAuthAccount({
      label: "antigravity-3",
      provider: "antigravity",
      credentials: {
        email: "dev@example.com",
        projectId: "proj-123",
      },
    })

    expect(upgradeOAuthAccountLabelIfNeeded(account)).toBe(true)
    expect(account.label).toBe("dev@example.com")
  })

  test("keeps custom labels untouched", () => {
    const account = createOAuthAccount({
      label: "My xAI Account",
      credentials: { email: "user@example.com" },
    })

    expect(upgradeOAuthAccountLabelIfNeeded(account)).toBe(false)
    expect(account.label).toBe("My xAI Account")
  })

  test("returns subtitle when different from label", () => {
    const account = createOAuthAccount({
      label: "My Account",
      credentials: { email: "user@example.com" },
    })
    expect(getOAuthAccountSubtitle(account)).toBe("user@example.com")
  })
})
