import { describe, expect, test } from "bun:test"

import { managedConnectionFromInput } from "~/lib/provider-connections"
import {
  followConnectionIdentityOnReauth,
  inferOAuthConnectionLabel,
  isAutoGeneratedOAuthLabel,
  isInferredOAuthLabel,
  upgradeOAuthConnectionLabelIfNeeded,
} from "~/services/oauth/account-label"

describe("oauth connection label helpers", () => {
  test("detects auto-generated provider labels", () => {
    expect(isAutoGeneratedOAuthLabel("xai-7", "xai")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("antigravity-8", "antigravity")).toBe(true)
    expect(isAutoGeneratedOAuthLabel("user@example.com", "xai")).toBe(false)
    expect(isAutoGeneratedOAuthLabel("custom-name", "xai")).toBe(false)
  })

  test("infers label from credential email", () => {
    const conn = managedConnectionFromInput({
      id: "test-id",
      name: "xai-1",
      provider: "xai",
      credentials: { accessToken: "t", email: "user@example.com" },
      settings: {},
    })
    expect(inferOAuthConnectionLabel(conn)).toBe("user@example.com")
  })

  test("upgrades an auto-generated label in place", () => {
    const conn = managedConnectionFromInput({
      id: "test-id",
      name: "xai-1",
      provider: "xai",
      credentials: { accessToken: "t", email: "user@example.com" },
      settings: {},
    })
    expect(upgradeOAuthConnectionLabelIfNeeded(conn)).toBe(true)
    expect(conn.name).toBe("user@example.com")
  })

  test("treats inferred identity labels as rewritable, custom names as not", () => {
    // 推断出来的名称：邮箱、裸 accountId、自动编号，都可以跟随身份改写。
    expect(isInferredOAuthLabel("old@example.com", "codex")).toBe(true)
    expect(
      isInferredOAuthLabel("f67f4aa8-58ce-45df-a68a-9bc906427deb", "codex"),
    ).toBe(true)
    expect(isInferredOAuthLabel("codex-2", "codex")).toBe(true)
    // 使用者自己起的名字：重建/重认证都不该抹掉。
    expect(isInferredOAuthLabel("我的笔记本", "codex")).toBe(false)
    expect(isInferredOAuthLabel("work account", "codex")).toBe(false)
  })

  test("re-auth follows the new identity when the name was itself inferred", () => {
    // 同一 ChatGPT 账号换邮箱重新登录：token 被回填进老连接，名称要跟上。
    const conn = managedConnectionFromInput({
      id: "test-id",
      name: "softeagle302@leihouwanglab886.com",
      provider: "codex",
      credentials: {
        accessToken: "t",
        email: "darktiger900@procsite.dpdns.org",
      },
      settings: {},
    })
    expect(followConnectionIdentityOnReauth(conn)).toBe(true)
    expect(conn.name).toBe("darktiger900@procsite.dpdns.org")
  })

  test("re-auth leaves a user-chosen name alone", () => {
    const conn = managedConnectionFromInput({
      id: "test-id",
      name: "我的 Codex 主力号",
      provider: "codex",
      credentials: {
        accessToken: "t",
        email: "darktiger900@procsite.dpdns.org",
      },
      settings: {},
    })
    expect(followConnectionIdentityOnReauth(conn)).toBe(false)
    expect(conn.name).toBe("我的 Codex 主力号")
  })

  test("re-auth is a no-op when the identity did not change", () => {
    const conn = managedConnectionFromInput({
      id: "test-id",
      name: "user@example.com",
      provider: "xai",
      credentials: { accessToken: "t", email: "user@example.com" },
      settings: {},
    })
    expect(followConnectionIdentityOnReauth(conn)).toBe(false)
    expect(conn.name).toBe("user@example.com")
  })
})
