/**
 * Builtin Provider Presets: 国内平台型与聚合中转服务商（豆包/火山、阿里百炼、小米、美团、Cline 等）
 */

import type { ProviderPreset } from "~/routes/admin/api/provider-presets-types"

export const DOMESTIC_SECONDARY_PRESETS: Array<ProviderPreset> = [
  {
    id: "doubao",
    name: "火山引擎 (豆包)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    authMode: "bearer",
    keyPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    portalUrl: "https://console.volcengine.com/ark",
    description: "字节跳动 Doubao Seed 2.0 / 1.6 系列",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "doubao-seed-2.0-pro",
        upstreamId: "doubao-seed-2.0-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "doubao-seed-2.0-code",
        upstreamId: "doubao-seed-2.0-code",
        endpoints: ["chat"],
      },
      {
        publicId: "doubao-seed-2.0-lite",
        upstreamId: "doubao-seed-2.0-lite",
        endpoints: ["chat"],
      },
      {
        publicId: "doubao-seed-1.6",
        upstreamId: "doubao-seed-1.6",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "doubao-anthropic",
    name: "火山引擎 (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    portalUrl: "https://console.volcengine.com/ark",
    description: "火山引擎 Coding Anthropic 兼容端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "doubao-seed-2.0-code",
        upstreamId: "doubao-seed-2.0-code",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "volcengine",
    name: "火山引擎 (聚合托管)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    authMode: "bearer",
    keyPlaceholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    portalUrl: "https://console.volcengine.com/ark",
    description: "火山方舟托管 DeepSeek V4 / V3.2、Kimi、GLM 与 MiniMax",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-v4-pro",
        upstreamId: "deepseek-v4-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v4-flash",
        upstreamId: "deepseek-v4-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v3.2",
        upstreamId: "deepseek-v3.2",
        endpoints: ["chat"],
      },
      {
        publicId: "minimax-m3",
        upstreamId: "minimax-m3",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-k2.6",
        upstreamId: "kimi-k2.6",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "bailian",
    name: "阿里百炼 (DashScope)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://bailian.console.aliyun.com/",
    description: "通义千问 Qwen3.7 / 3.6 / Coder、DeepSeek V4 等全系",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "qwen3.7-max",
        upstreamId: "qwen3.7-max",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen3.7-plus",
        upstreamId: "qwen3.7-plus",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen3.6-plus",
        upstreamId: "qwen3.6-plus",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen3.6-flash",
        upstreamId: "qwen3.6-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen3-coder-plus",
        upstreamId: "qwen3-coder-plus",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v4-pro",
        upstreamId: "deepseek-v4-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v4-flash",
        upstreamId: "deepseek-v4-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v3.2",
        upstreamId: "deepseek-v3.2",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-k2.6",
        upstreamId: "kimi-k2.6",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "bailian-anthropic",
    name: "阿里百炼 (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://bailian.console.aliyun.com/",
    description: "阿里百炼 Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "qwen3.7-max",
        upstreamId: "qwen3.7-max",
        endpoints: ["messages"],
      },
      {
        publicId: "qwen3.7-plus",
        upstreamId: "qwen3.7-plus",
        endpoints: ["messages"],
      },
      {
        publicId: "qwen3-coder-plus",
        upstreamId: "qwen3-coder-plus",
        endpoints: ["messages"],
      },
      {
        publicId: "deepseek-v4-pro",
        upstreamId: "deepseek-v4-pro",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo (小米)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.xiaomimimo.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://xiaomimimo.com",
    description: "小米 MiMo v2.5 / v2.5-pro 大模型平台",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "mimo-v2.5-pro",
        upstreamId: "mimo-v2.5-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "mimo-v2.5",
        upstreamId: "mimo-v2.5",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "xiaomi-anthropic",
    name: "Xiaomi MiMo (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://xiaomimimo.com",
    description: "小米 MiMo Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "mimo-v2.5-pro",
        upstreamId: "mimo-v2.5-pro",
        endpoints: ["messages"],
      },
      {
        publicId: "mimo-v2.5",
        upstreamId: "mimo-v2.5",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "longcat",
    name: "LongCat (美团)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.longcat.chat/openai/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://longcat.chat",
    description: "美团 LongCat 闪速推理服务",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "LongCat-Flash-Chat",
        upstreamId: "LongCat-Flash-Chat",
        endpoints: ["chat"],
      },
      {
        publicId: "LongCat-Flash-Thinking",
        upstreamId: "LongCat-Flash-Thinking",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "longcat-anthropic",
    name: "LongCat (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.longcat.chat/anthropic",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://longcat.chat",
    description: "美团 LongCat Anthropic 兼容端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "LongCat-Flash-Chat",
        upstreamId: "LongCat-Flash-Chat",
        endpoints: ["messages"],
      },
      {
        publicId: "LongCat-Flash-Thinking",
        upstreamId: "LongCat-Flash-Thinking",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "modelscope",
    name: "ModelScope (魔搭)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://modelscope.cn",
    description: "阿里魔搭社区开源推理 API",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "qwen-plus",
        upstreamId: "qwen-plus",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen-max",
        upstreamId: "qwen-max",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen2.5-72b-instruct",
        upstreamId: "qwen2.5-72b-instruct",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "qiniu",
    name: "Qiniu (七牛云)",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.qnaigc.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://qnaigc.com",
    description: "七牛云 AI 托管服务",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-v3",
        upstreamId: "deepseek-v3",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "qiniu-anthropic",
    name: "Qiniu (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.qnaigc.com",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://qnaigc.com",
    description: "七牛云 Anthropic 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-v3",
        upstreamId: "deepseek-v3",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "cline",
    name: "Cline Pass",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://api.cline.bot/api/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://cline.bot",
    description: "Cline 专属中转服务（含 DeepSeek V4、Qwen3.7、GLM-5.2 等）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "cline-pass/deepseek-v4-flash",
        upstreamId: "cline-pass/deepseek-v4-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "cline-pass/deepseek-v4-pro",
        upstreamId: "cline-pass/deepseek-v4-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "cline-pass/qwen3.7-plus",
        upstreamId: "cline-pass/qwen3.7-plus",
        endpoints: ["chat"],
      },
      {
        publicId: "cline-pass/glm-5.2",
        upstreamId: "cline-pass/glm-5.2",
        endpoints: ["chat"],
      },
      {
        publicId: "cline-pass/kimi-k2.7-code",
        upstreamId: "cline-pass/kimi-k2.7-code",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    category: "domestic",
    protocol: "openai-compatible",
    baseUrl: "https://opencode.ai/zen/go",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://opencode.ai",
    description: "OpenCode Go 专属编程代理端点 (/zen/go)",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "glm-5.1",
        upstreamId: "glm-5.1",
        endpoints: ["chat"],
      },
      {
        publicId: "glm-5",
        upstreamId: "glm-5",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v4-pro",
        upstreamId: "deepseek-v4-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "kimi-k2.6",
        upstreamId: "kimi-k2.6",
        endpoints: ["chat"],
      },
      {
        publicId: "mimo-v2.5-pro",
        upstreamId: "mimo-v2.5-pro",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "opencode-go-anthropic",
    name: "OpenCode Go (Anthropic 兼容)",
    category: "domestic",
    protocol: "anthropic-compatible",
    baseUrl: "https://opencode.ai/zen/go",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://opencode.ai",
    description: "OpenCode Go Anthropic 原生协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "minimax-m3",
        upstreamId: "minimax-m3",
        endpoints: ["messages"],
      },
      {
        publicId: "minimax-m2.7",
        upstreamId: "minimax-m2.7",
        endpoints: ["messages"],
      },
      {
        publicId: "qwen3.7-max",
        upstreamId: "qwen3.7-max",
        endpoints: ["messages"],
      },
      {
        publicId: "qwen3.7-plus",
        upstreamId: "qwen3.7-plus",
        endpoints: ["messages"],
      },
    ],
  },
]
