/**
 * Builtin Provider Presets: 海外大厂、聚合中转与本地自建
 *
 * 参考 axonhub 官方配置同步最新 2026 前沿大模型体系。
 */

import type { ProviderPreset } from "~/routes/admin/api/provider-presets-types"

export const OTHERS_PRESETS: Array<ProviderPreset> = [
  // ── 海外大厂 (international) ──
  {
    id: "openai",
    name: "OpenAI",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-proj-...",
    portalUrl: "https://platform.openai.com/api-keys",
    description: "GPT-5.2 / GPT-5.1 / GPT-4o / o3 / o4 系列官方 API",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "gpt-5.2", upstreamId: "gpt-5.2", endpoints: ["chat"] },
      { publicId: "gpt-5.1", upstreamId: "gpt-5.1", endpoints: ["chat"] },
      { publicId: "gpt-5", upstreamId: "gpt-5", endpoints: ["chat"] },
      { publicId: "gpt-4o", upstreamId: "gpt-4o", endpoints: ["chat"] },
      {
        publicId: "gpt-4o-mini",
        upstreamId: "gpt-4o-mini",
        endpoints: ["chat"],
      },
      { publicId: "gpt-4.1", upstreamId: "gpt-4.1", endpoints: ["chat"] },
      { publicId: "o3", upstreamId: "o3", endpoints: ["chat"] },
      { publicId: "o4-mini", upstreamId: "o4-mini", endpoints: ["chat"] },
    ],
  },
  {
    id: "openai-responses",
    name: "OpenAI (Responses API)",
    category: "international",
    protocol: "openai-responses-compatible",
    baseUrl: "https://api.openai.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-proj-...",
    portalUrl: "https://platform.openai.com/api-keys",
    description: "OpenAI 原生 Responses / Codex 协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "gpt-5.2", upstreamId: "gpt-5.2", endpoints: ["responses"] },
      {
        publicId: "gpt-5.2-codex",
        upstreamId: "gpt-5.2-codex",
        endpoints: ["responses"],
      },
      { publicId: "gpt-5", upstreamId: "gpt-5", endpoints: ["responses"] },
      { publicId: "gpt-4o", upstreamId: "gpt-4o", endpoints: ["responses"] },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    category: "international",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.anthropic.com",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-ant-...",
    portalUrl: "https://console.anthropic.com/settings/keys",
    description: "Claude Opus 4.5 / Sonnet 4.5 / Haiku 4.5 系列官方 API",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "claude-opus-4-5",
        upstreamId: "claude-opus-4-5",
        endpoints: ["messages"],
      },
      {
        publicId: "claude-sonnet-4-5",
        upstreamId: "claude-sonnet-4-5",
        endpoints: ["messages"],
      },
      {
        publicId: "claude-haiku-4-5",
        upstreamId: "claude-haiku-4-5",
        endpoints: ["messages"],
      },
      {
        publicId: "claude-3-7-sonnet-20250219",
        upstreamId: "claude-3-7-sonnet-20250219",
        endpoints: ["messages"],
      },
      {
        publicId: "claude-3-5-sonnet-20241022",
        upstreamId: "claude-3-5-sonnet-20241022",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "gemini-openai",
    name: "Google Gemini (OpenAI 兼容)",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    authMode: "bearer",
    keyPlaceholder: "AIzaSy...",
    portalUrl: "https://aistudio.google.com/app/apikey",
    description: "Google Gemini 3.0 / 2.5 Pro & Flash 官方兼容端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "gemini-3-pro",
        upstreamId: "gemini-3-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-3-flash",
        upstreamId: "gemini-3-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-2.5-pro",
        upstreamId: "gemini-2.5-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-2.5-flash",
        upstreamId: "gemini-2.5-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-2.0-flash",
        upstreamId: "gemini-2.0-flash",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.x.ai/v1",
    authMode: "bearer",
    keyPlaceholder: "xai-...",
    portalUrl: "https://console.x.ai/",
    description: "xAI Grok-4 / Grok-3 / Grok Code Fast 系列官方 API",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "grok-4", upstreamId: "grok-4", endpoints: ["chat"] },
      {
        publicId: "grok-4-fast-reasoning",
        upstreamId: "grok-4-fast-reasoning",
        endpoints: ["chat"],
      },
      {
        publicId: "grok-4-fast-non-reasoning",
        upstreamId: "grok-4-fast-non-reasoning",
        endpoints: ["chat"],
      },
      { publicId: "grok-3", upstreamId: "grok-3", endpoints: ["chat"] },
      {
        publicId: "grok-3-mini",
        upstreamId: "grok-3-mini",
        endpoints: ["chat"],
      },
      {
        publicId: "grok-code-fast",
        upstreamId: "grok-code-fast",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.groq.com/openai/v1",
    authMode: "bearer",
    keyPlaceholder: "gsk_...",
    portalUrl: "https://console.groq.com/keys",
    description:
      "Groq LPU 超极速推理（GPT-OSS / Llama 3.3 / DeepSeek R1 蒸馏）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "openai/gpt-oss-120b",
        upstreamId: "openai/gpt-oss-120b",
        endpoints: ["chat"],
      },
      {
        publicId: "openai/gpt-oss-20b",
        upstreamId: "openai/gpt-oss-20b",
        endpoints: ["chat"],
      },
      {
        publicId: "llama-3.3-70b-versatile",
        upstreamId: "llama-3.3-70b-versatile",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-r1-distill-llama-70b",
        upstreamId: "deepseek-r1-distill-llama-70b",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.cerebras.ai/v1",
    authMode: "bearer",
    keyPlaceholder: "csk-...",
    portalUrl: "https://cloud.cerebras.ai/",
    description: "晶圆级超高吞吐推理平台",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "llama-3.3-70b",
        upstreamId: "llama-3.3-70b",
        endpoints: ["chat"],
      },
      {
        publicId: "llama3.1-70b",
        upstreamId: "llama3.1-70b",
        endpoints: ["chat"],
      },
      {
        publicId: "llama3.1-8b",
        upstreamId: "llama3.1-8b",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://deepinfra.com/dash/api_keys",
    description: "高性价比开源模型推理（DeepSeek V3.2 / Kimi K2 / Qwen）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-ai/DeepSeek-V3.2",
        upstreamId: "deepseek-ai/DeepSeek-V3.2",
        endpoints: ["chat"],
      },
      {
        publicId: "moonshotai/Kimi-K2-Thinking",
        upstreamId: "moonshotai/Kimi-K2-Thinking",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-ai/DeepSeek-V3",
        upstreamId: "deepseek-ai/DeepSeek-V3",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-ai/DeepSeek-R1",
        upstreamId: "deepseek-ai/DeepSeek-R1",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    authMode: "bearer",
    keyPlaceholder: "fw_...",
    portalUrl: "https://fireworks.ai/account/api-keys",
    description: "企业级极速推理引擎（GLM-5 / MiniMax / Kimi）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "accounts/fireworks/models/glm-5",
        upstreamId: "accounts/fireworks/models/glm-5",
        endpoints: ["chat"],
      },
      {
        publicId: "accounts/fireworks/models/minimax-m2p5",
        upstreamId: "accounts/fireworks/models/minimax-m2p5",
        endpoints: ["chat"],
      },
      {
        publicId: "accounts/fireworks/models/kimi-k2p5",
        upstreamId: "accounts/fireworks/models/kimi-k2p5",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "github",
    name: "GitHub Models",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://models.github.ai/inference",
    authMode: "bearer",
    keyPlaceholder: "ghp_...",
    portalUrl: "https://github.com/marketplace/models",
    description:
      "GitHub 托管主流大模型（GPT-4.1 / Claude Sonnet 4 / DeepSeek V3）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "openai/gpt-4.1",
        upstreamId: "openai/gpt-4.1",
        endpoints: ["chat"],
      },
      {
        publicId: "openai/gpt-4o",
        upstreamId: "openai/gpt-4o",
        endpoints: ["chat"],
      },
      { publicId: "openai/o3", upstreamId: "openai/o3", endpoints: ["chat"] },
      {
        publicId: "openai/o4-mini",
        upstreamId: "openai/o4-mini",
        endpoints: ["chat"],
      },
      {
        publicId: "anthropic/claude-sonnet-4",
        upstreamId: "anthropic/claude-sonnet-4",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek/DeepSeek-V3-0324",
        upstreamId: "deepseek/DeepSeek-V3-0324",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "jina",
    name: "Jina AI",
    category: "international",
    protocol: "openai-compatible",
    baseUrl: "https://api.jina.ai/v1",
    authMode: "bearer",
    keyPlaceholder: "jina_...",
    portalUrl: "https://jina.ai",
    description: "Jina Embeddings v3 多语言向量表征 API",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "jina-embeddings-v3",
        upstreamId: "jina-embeddings-v3",
        endpoints: ["embeddings"],
      },
    ],
  },

  // ── 聚合中转 (aggregator) ──
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://openrouter.ai/api/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-or-v1-...",
    portalUrl: "https://openrouter.ai/keys",
    description: "聚合全球数百种顶级大模型路由",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "anthropic/claude-sonnet-4",
        upstreamId: "anthropic/claude-sonnet-4",
        endpoints: ["chat"],
      },
      {
        publicId: "anthropic/claude-opus-4",
        upstreamId: "anthropic/claude-opus-4",
        endpoints: ["chat"],
      },
      {
        publicId: "moonshotai/kimi-k2-0905",
        upstreamId: "moonshotai/kimi-k2-0905",
        endpoints: ["chat"],
      },
      {
        publicId: "z-ai/glm-4.7",
        upstreamId: "z-ai/glm-4.7",
        endpoints: ["chat"],
      },
      {
        publicId: "openai/gpt-4o",
        upstreamId: "openai/gpt-4o",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://aihubmix.com/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://aihubmix.com",
    description:
      "多厂商大模型聚合中转服务（DeepSeek V3.2 / Claude 4.5 / Gemini 3）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "DeepSeek-V3.2-Exp",
        upstreamId: "DeepSeek-V3.2-Exp",
        endpoints: ["chat"],
      },
      {
        publicId: "claude-sonnet-4-5",
        upstreamId: "claude-sonnet-4-5",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-3-pro",
        upstreamId: "gemini-3-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-3-flash",
        upstreamId: "gemini-3-flash",
        endpoints: ["chat"],
      },
      { publicId: "gpt-4o", upstreamId: "gpt-4o", endpoints: ["chat"] },
      { publicId: "glm-4.7", upstreamId: "glm-4.7", endpoints: ["chat"] },
      {
        publicId: "Kimi-K2-0905",
        upstreamId: "Kimi-K2-0905",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "aihubmix-anthropic",
    name: "AiHubMix (Anthropic 兼容)",
    category: "aggregator",
    protocol: "anthropic-compatible",
    baseUrl: "https://aihubmix.com",
    authMode: "header",
    headerName: "x-api-key",
    keyPlaceholder: "sk-...",
    portalUrl: "https://aihubmix.com",
    description: "AiHubMix Anthropic 原生协议端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "claude-sonnet-4-5",
        upstreamId: "claude-sonnet-4-5",
        endpoints: ["messages"],
      },
      {
        publicId: "DeepSeek-V3.2-Exp",
        upstreamId: "DeepSeek-V3.2-Exp",
        endpoints: ["messages"],
      },
      {
        publicId: "gemini-3-pro",
        upstreamId: "gemini-3-pro",
        endpoints: ["messages"],
      },
    ],
  },
  {
    id: "ppio",
    name: "PPIO",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://api.ppinfra.com/openai/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://ppinfra.com",
    description: "PPIO 边缘云大模型（DeepSeek V3.2 / Qwen3 Coder / GLM-4.6）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek/deepseek-v3.2-exp",
        upstreamId: "deepseek/deepseek-v3.2-exp",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek/deepseek-v3.1",
        upstreamId: "deepseek/deepseek-v3.1",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek/deepseek-r1-0528",
        upstreamId: "deepseek/deepseek-r1-0528",
        endpoints: ["chat"],
      },
      {
        publicId: "qwen/qwen3-coder-480b-a35b-instruct",
        upstreamId: "qwen/qwen3-coder-480b-a35b-instruct",
        endpoints: ["chat"],
      },
      {
        publicId: "zai-org/glm-4.6",
        upstreamId: "zai-org/glm-4.6",
        endpoints: ["chat"],
      },
      {
        publicId: "moonshotai/kimi-k2-0905",
        upstreamId: "moonshotai/kimi-k2-0905",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "evolink",
    name: "Evolink",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://direct.evolink.ai/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://evolink.ai",
    description:
      "Evolink 智能路由（GPT-5.2 / DeepSeek V4 / Gemini 3.0 / Claude）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "gpt-5.2", upstreamId: "gpt-5.2", endpoints: ["chat"] },
      { publicId: "gpt-5.4", upstreamId: "gpt-5.4", endpoints: ["chat"] },
      {
        publicId: "deepseek-v4-pro",
        upstreamId: "deepseek-v4-pro",
        endpoints: ["chat"],
      },
      {
        publicId: "deepseek-v4-flash",
        upstreamId: "deepseek-v4-flash",
        endpoints: ["chat"],
      },
      {
        publicId: "gemini-3.0-pro",
        upstreamId: "gemini-3.0-pro",
        endpoints: ["chat"],
      },
      { publicId: "minimax-m3", upstreamId: "minimax-m3", endpoints: ["chat"] },
    ],
  },
  {
    id: "vercel",
    name: "Vercel AI Gateway",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://vercel.com",
    description: "Vercel 边缘 AI 网关（DeepSeek V3.2 / Kimi K2）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek/deepseek-v3.2-exp",
        upstreamId: "deepseek/deepseek-v3.2-exp",
        endpoints: ["chat"],
      },
      {
        publicId: "moonshotai/kimi-k2-thinking",
        upstreamId: "moonshotai/kimi-k2-thinking",
        endpoints: ["chat"],
      },
      {
        publicId: "moonshotai/kimi-k2",
        upstreamId: "moonshotai/kimi-k2",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "atlascloud",
    name: "AtlasCloud",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://api.atlascloud.ai/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://atlascloud.ai",
    description:
      "AtlasCloud 智算平台（DeepSeek V3 / Qwen / Kimi K2 / GLM-4.7）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "deepseek-v3",
        upstreamId: "deepseek-v3",
        endpoints: ["chat"],
      },
      { publicId: "qwen-plus", upstreamId: "qwen-plus", endpoints: ["chat"] },
      { publicId: "kimi-k2", upstreamId: "kimi-k2", endpoints: ["chat"] },
      { publicId: "glm-4.7", upstreamId: "glm-4.7", endpoints: ["chat"] },
    ],
  },
  {
    id: "nanogpt",
    name: "NanoGPT",
    category: "aggregator",
    protocol: "openai-compatible",
    baseUrl: "https://nano-gpt.com/api/v1",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://nano-gpt.com",
    description: "NanoGPT 聚合与即用 API（GLM-4.7 / GLM-4.6 / Flux）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      {
        publicId: "zai-org/glm-4.7:thinking",
        upstreamId: "zai-org/glm-4.7:thinking",
        endpoints: ["chat"],
      },
      {
        publicId: "zai-org/glm-4.7",
        upstreamId: "zai-org/glm-4.7",
        endpoints: ["chat"],
      },
      {
        publicId: "zai-org/glm-4.6",
        upstreamId: "zai-org/glm-4.6",
        endpoints: ["chat"],
      },
      {
        publicId: "flux-kontext",
        upstreamId: "flux-kontext",
        endpoints: ["chat"],
      },
    ],
  },
  {
    id: "fenno",
    name: "Fenno AI",
    category: "aggregator",
    protocol: "openai-responses-compatible",
    baseUrl: "https://api.fenno.ai",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    portalUrl: "https://fenno.ai",
    description: "Fenno AI Responses / Codex 转发端点",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "gpt-5.2", upstreamId: "gpt-5.2", endpoints: ["responses"] },
      {
        publicId: "gpt-5.2-codex",
        upstreamId: "gpt-5.2-codex",
        endpoints: ["responses"],
      },
    ],
  },

  // ── 本地与自建 (local) ──
  {
    id: "ollama",
    name: "Ollama (本地运行)",
    category: "local",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:11434/v1",
    authMode: "bearer",
    keyPlaceholder: "无需 API Key（留空即可）",
    portalUrl: "https://ollama.com",
    description: "本地运行的大模型（支持在线探测一键获取全部已下载模型）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [
      { publicId: "llama3.2", upstreamId: "llama3.2", endpoints: ["chat"] },
      { publicId: "llama3.1", upstreamId: "llama3.1", endpoints: ["chat"] },
      { publicId: "qwen2.5", upstreamId: "qwen2.5", endpoints: ["chat"] },
      { publicId: "mistral", upstreamId: "mistral", endpoints: ["chat"] },
    ],
  },
  {
    id: "vllm",
    name: "vLLM (自建 / 本地)",
    category: "local",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:8000/v1",
    authMode: "bearer",
    keyPlaceholder: "可选，若无密码留空即可",
    portalUrl: "https://vllm.ai",
    description: "高吞吐量开源 LLM 推理服务（支持在线探测一键获取模型）",
    fetchable: true,
    discoveryEnabled: true,
    discoveryMode: "merge",
    defaultModels: [],
  },
  {
    id: "custom",
    name: "自定义 Provider",
    category: "custom",
    protocol: "openai-compatible",
    baseUrl: "",
    authMode: "bearer",
    keyPlaceholder: "sk-...",
    description: "自由配置任意 OpenAI 或 Anthropic 兼容端点",
    fetchable: true,
    discoveryEnabled: false,
    discoveryMode: "merge",
    defaultModels: [],
  },
]
