import type { ProviderConnection } from "~/lib/provider-connections"

import {
  getConnectionProvider,
  getCredentialContextString,
  isOAuthConnection,
  providerFromProtocol,
} from "~/lib/provider-connections"

export function isAutoGeneratedOAuthLabel(
  label: string,
  provider: string,
): boolean {
  const trimmed = label.trim()
  if (!trimmed) return true
  const escaped = provider.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)
  return new RegExp(String.raw`^${escaped}-\d+$`, "i").test(trimmed)
}

/**
 * 从 connection 的 credential.context 推断 OAuth label。
 * 镜像 inferOAuthAccountLabel,但直接读 connection 字段。
 */
export function inferOAuthConnectionLabel(
  conn: ProviderConnection,
): string | undefined {
  const email = getCredentialContextString(conn, "email")?.trim()
  if (email) return email

  const accountId = getCredentialContextString(conn, "oauthAccountId")?.trim()
  if (accountId) return accountId

  const projectId = getCredentialContextString(conn, "projectId")?.trim()
  const provider = getConnectionProvider(conn)
  if (provider === "antigravity" && projectId) {
    return projectId.length > 24 ?
        `Antigravity (${projectId.slice(0, 8)}…)`
      : projectId
  }

  return undefined
}

const UUID_LABEL_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const EMAIL_LABEL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

/**
 * 名称本身是否就是"推断出来的身份"（自动生成的 `codex-1`、一个邮箱，或一个
 * 裸 accountId），而非使用者自己起的名字。
 *
 * 只有这一类名称才允许被新的身份改写（见 followConnectionIdentityOnReauth）。
 * `我的笔记本` 这类自定义名称永远不动——重建账号不该抹掉使用者的命名。
 */
export function isInferredOAuthLabel(label: string, provider: string): boolean {
  if (isAutoGeneratedOAuthLabel(label, provider)) return true
  const trimmed = label.trim()
  return UUID_LABEL_RE.test(trimmed) || EMAIL_LABEL_RE.test(trimmed)
}

/**
 * 重新认证把新身份回填进已有 connection 之后，让连接名跟上身份。
 *
 * 背景：`findConnectionByOAuthIdentity` 按身份判重后，新登录的 token 会被
 * 回填进匹配到的老连接（避免两份 refresh token 互相作废），但老连接的
 * name 仍是它当初推断出的旧邮箱——于是界面标题与副标题是两个邮箱，看起来
 * 像"新账号没添加"。显式 `reauthAccountId` 重登到不同账号时同理。
 *
 * 只在 name 本身属于推断标签时才改写；自定义名称原样保留。
 * 返回 true 表示名称已跟随身份更新。
 */
export function followConnectionIdentityOnReauth(
  conn: ProviderConnection,
): boolean {
  const provider = providerFromProtocol(conn.protocol)
  if (!provider || !isOAuthConnection(conn)) return false
  if (!isInferredOAuthLabel(conn.name, provider)) return false

  const inferred = inferOAuthConnectionLabel(conn)
  if (!inferred || inferred === conn.name) return false

  conn.name = inferred
  conn.updatedAt = Date.now()
  return true
}

/**
 * 如果 connection 的 label 是自动生成的(如 "claude-1"),
 * 尝试从 credential.context 推断更好的 label 并更新 conn.name。
 * 镜像 upgradeOAuthAccountLabelIfNeeded,但直接操作 connection。
 * 返回 true 表示 label 被升级。
 */
export function upgradeOAuthConnectionLabelIfNeeded(
  conn: ProviderConnection,
): boolean {
  const provider = providerFromProtocol(conn.protocol)
  if (!provider || !isOAuthConnection(conn)) return false

  if (!isAutoGeneratedOAuthLabel(conn.name, provider)) {
    return false
  }

  const inferred = inferOAuthConnectionLabel(conn)
  if (!inferred || inferred === conn.name) {
    return false
  }

  conn.name = inferred
  return true
}

/**
 * 批量升级 OAuth connection 的 label。
 * 镜像 upgradeOAuthAccountLabels,但直接操作 connection 数组。
 * 返回 true 表示至少一个 connection 的 label 被升级。
 */
export function upgradeOAuthConnectionLabels(
  connections: Array<ProviderConnection>,
): boolean {
  let changed = false
  for (const conn of connections) {
    if (!isOAuthConnection(conn)) continue
    if (upgradeOAuthConnectionLabelIfNeeded(conn)) {
      changed = true
    }
  }
  return changed
}
