import type { OAuthAccount } from "~/lib/accounts"

import { isOAuthAccount, type Account } from "~/lib/accounts"

export function isAutoGeneratedOAuthLabel(
  label: string,
  provider: string,
): boolean {
  const trimmed = label.trim()
  if (!trimmed) return true
  const escaped = provider.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)
  return new RegExp(String.raw`^${escaped}-\d+$`, "i").test(trimmed)
}

export function inferOAuthAccountLabel(
  account: OAuthAccount,
): string | undefined {
  const email = account.credentials?.email?.trim()
  if (email) return email

  const accountId = account.credentials?.accountId?.trim()
  if (accountId) return accountId

  const projectId = account.credentials?.projectId?.trim()
  if (account.provider === "antigravity" && projectId) {
    return projectId.length > 24 ?
        `Antigravity (${projectId.slice(0, 8)}…)`
      : projectId
  }

  return undefined
}

export function upgradeOAuthAccountLabelIfNeeded(
  account: OAuthAccount,
): boolean {
  if (!isAutoGeneratedOAuthLabel(account.label, account.provider)) {
    return false
  }

  const inferred = inferOAuthAccountLabel(account)
  if (!inferred || inferred === account.label) {
    return false
  }

  account.label = inferred
  return true
}

export function upgradeOAuthAccountLabels(accounts: Array<Account>): boolean {
  let changed = false
  for (const account of accounts) {
    if (!isOAuthAccount(account)) continue
    if (upgradeOAuthAccountLabelIfNeeded(account)) {
      changed = true
    }
  }
  return changed
}

export function getOAuthAccountSubtitle(
  account: OAuthAccount,
): string | undefined {
  const email = account.credentials?.email?.trim()
  if (email && email !== account.label) {
    return email
  }

  const projectId = account.credentials?.projectId?.trim()
  if (
    account.provider === "antigravity"
    && projectId
    && projectId !== account.label
  ) {
    return projectId
  }

  const accountId = account.credentials?.accountId?.trim()
  if (accountId && accountId !== account.label) {
    return accountId
  }

  return undefined
}
