import type { OAuthAccount } from "~/lib/legacy-accounts"
import type { ProviderConnection } from "~/lib/provider-connections"

import {
  getConnectionProvider,
  getCredentialContextString,
  isOAuthConnection,
  providerFromProtocol,
} from "~/lib/provider-connections"

export function isAutoGeneratedOAuthLabel(
  label: string,
  provider: string,
): boolean {
  const trimmed = label.trim()
  if (!trimmed) return true
  const escaped = provider.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)
  return new RegExp(String.raw`^${escaped}-\d+$`, "i").test(trimmed)
}

// Phase 3.4:已删除 inferOAuthAccountLabel(account) / upgradeOAuthAccountLabelIfNeeded(account) /
// upgradeOAuthAccountLabels(accounts) —— 无生产调用方,被 connection 原生版本替代。
// getOAuthAccountSubtitle(account) 保留:admin API (accounts.ts / quota.ts) 仍用它派生
// publicAccount 的 subtitle 字段。

export function getOAuthAccountSubtitle(
  account: OAuthAccount,
): string | undefined {
  const email = account.credentials?.email?.trim()
  if (email && email !== account.label) {
    return email
  }

  const projectId = account.credentials?.projectId?.trim()
  if (
    account.provider === "antigravity"
    && projectId
    && projectId !== account.label
  ) {
    return projectId
  }

  const accountId = account.credentials?.accountId?.trim()
  if (accountId && accountId !== account.label) {
    return accountId
  }

  return undefined
}

// ── Connection 原生版本(替代 Account 级 label upgrade) ──────────

/**
 * 从 connection 的 credential.context 推断 OAuth label。
 * 镜像 inferOAuthAccountLabel,但直接读 connection 字段。
 */
export function inferOAuthConnectionLabel(
  conn: ProviderConnection,
): string | undefined {
  const email = getCredentialContextString(conn, "email")?.trim()
  if (email) return email

  const accountId = getCredentialContextString(conn, "oauthAccountId")?.trim()
  if (accountId) return accountId

  const projectId = getCredentialContextString(conn, "projectId")?.trim()
  const provider = getConnectionProvider(conn)
  if (provider === "antigravity" && projectId) {
    return projectId.length > 24 ?
        `Antigravity (${projectId.slice(0, 8)}…)`
      : projectId
  }

  return undefined
}

/**
 * 如果 connection 的 label 是自动生成的(如 "claude-1"),
 * 尝试从 credential.context 推断更好的 label 并更新 conn.name。
 * 镜像 upgradeOAuthAccountLabelIfNeeded,但直接操作 connection。
 * 返回 true 表示 label 被升级。
 */
export function upgradeOAuthConnectionLabelIfNeeded(
  conn: ProviderConnection,
): boolean {
  const provider = providerFromProtocol(conn.protocol)
  if (!provider || !isOAuthConnection(conn)) return false

  if (!isAutoGeneratedOAuthLabel(conn.name, provider)) {
    return false
  }

  const inferred = inferOAuthConnectionLabel(conn)
  if (!inferred || inferred === conn.name) {
    return false
  }

  conn.name = inferred
  return true
}

/**
 * 批量升级 OAuth connection 的 label。
 * 镜像 upgradeOAuthAccountLabels,但直接操作 connection 数组。
 * 返回 true 表示至少一个 connection 的 label 被升级。
 */
export function upgradeOAuthConnectionLabels(
  connections: Array<ProviderConnection>,
): boolean {
  let changed = false
  for (const conn of connections) {
    if (!isOAuthConnection(conn)) continue
    if (upgradeOAuthConnectionLabelIfNeeded(conn)) {
      changed = true
    }
  }
  return changed
}
