/**
 * CodeBuddy OAuth 设备授权登录。
 *
 * 对齐 workbuddy2api `cmd/login` 的设备流（无 PKCE，state 由服务端签发）：
 *   1. `POST {base}/v2/plugin/auth/state?platform=CLI` → `{state, authUrl}`
 *   2. 用户在浏览器打开 `authUrl` 完成登录
 *   3. `GET {base}/v2/plugin/auth/token?state=` 轮询 → `{accessToken, refreshToken, expiresIn, domain}`
 *      （pending 时业务 code 非 0，完成时 code=0）
 *   4. `GET {base}/v2/plugin/login/account?state=`（带 Bearer）→ `{uid, enterpriseId, nickname}`
 *
 * 双 realm（与 provider id 对应）：
 *   - `codebuddy`（国际版）：`https://www.codebuddy.ai`
 *   - `codebuddy-cn`（国内版）：`https://copilot.tencent.com`
 */

import type { ProviderConnection } from "~/lib/provider-connections"

import { ensureLegacyMetadata } from "~/lib/provider-connections"
import { logger } from "~/lib/logger"

import { isAutoGeneratedOAuthLabel } from "./account-label"
import { applyOAuthBundleToCredential } from "./apply-bundle"
import { oauthFetch, type OAuthFetchOptions } from "./fetch"

export const CODEBUDDY_OAUTH_PROVIDER_IDS = [
  "codebuddy",
  "codebuddy-cn",
] as const

export type CodebuddyOAuthProviderId =
  (typeof CODEBUDDY_OAUTH_PROVIDER_IDS)[number]

export function isCodebuddyOAuthProviderId(
  value: string,
): value is CodebuddyOAuthProviderId {
  return (CODEBUDDY_OAUTH_PROVIDER_IDS as ReadonlyArray<string>).includes(value)
}

interface CodebuddyRealmConfig {
  base: string
  origin: string
  domain: string
}

export function codebuddyRealmConfig(
  provider: CodebuddyOAuthProviderId,
): CodebuddyRealmConfig {
  if (provider === "codebuddy-cn") {
    return {
      base: "https://copilot.tencent.com",
      origin: "https://www.codebuddy.cn",
      domain: "www.codebuddy.cn",
    }
  }
  return {
    base: "https://www.codebuddy.ai",
    origin: "https://www.codebuddy.ai",
    domain: "www.codebuddy.ai",
  }
}

const CODEBUDDY_USER_AGENT = "CLI/2.148.0 CodeBuddy/2.148.0"
const CODEBUDDY_CHECKIN_URL =
  "https://www.codebuddy.cn/v2/billing/meter/daily-checkin"

const DEFAULT_POLL_INTERVAL_MS = 5000
const DEFAULT_POLL_TIMEOUT_MS = 15 * 60 * 1000

function codebuddyOAuthHeaders(origin: string): Record<string, string> {
  return {
    "Content-Type": "application/json",
    Accept: "application/json, text/plain, */*",
    "X-Requested-With": "XMLHttpRequest",
    Origin: origin,
    Referer: `${origin}/`,
    "User-Agent": CODEBUDDY_USER_AGENT,
  }
}

interface CodebuddyEnvelope {
  code?: number
  msg?: string
  data?: Record<string, unknown>
}

function readString(data: Record<string, unknown>, key: string): string {
  const value = data[key]
  return typeof value === "string" ? value : ""
}

function readNumber(data: Record<string, unknown>, key: string): number {
  const value = data[key]
  return typeof value === "number" ? value : 0
}

async function readEnvelopeData(
  response: Response,
  what: string,
): Promise<Record<string, unknown>> {
  if (!response.ok) {
    throw new Error(`CodeBuddy OAuth ${what} failed: HTTP ${response.status}`)
  }
  const body = (await response.json()) as CodebuddyEnvelope
  if (body.code !== 0 || !body.data || typeof body.data !== "object") {
    throw new Error(
      `CodeBuddy OAuth ${what} failed: code=${body.code ?? "?"} msg=${body.msg ?? ""}`,
    )
  }
  return body.data
}

export interface CodebuddyAuthState {
  state: string
  authUrl: string
}

/**
 * 设备流第 1 步：取服务端签发的 state + 浏览器授权 URL。
 */
export async function startCodebuddyDeviceFlow(
  provider: CodebuddyOAuthProviderId,
  options?: OAuthFetchOptions,
): Promise<CodebuddyAuthState> {
  const { base, origin } = codebuddyRealmConfig(provider)
  const response = await oauthFetch(
    `${base}/v2/plugin/auth/state?platform=CLI`,
    {
      method: "POST",
      headers: codebuddyOAuthHeaders(origin),
      body: "{}",
    },
    options,
  )
  const data = await readEnvelopeData(response, "auth state")
  const state = readString(data, "state")
  const authUrl = readString(data, "authUrl")
  if (!state || !authUrl) {
    throw new Error(
      "CodeBuddy OAuth auth state returned empty state or authUrl",
    )
  }
  return { state, authUrl }
}

interface CodebuddyTokenData {
  accessToken: string
  refreshToken: string
  expiresIn: number
  domain: string
}

/**
 * token 端点单次查询：完成返回 token 数据，pending 返回 null，
 * 服务端 5xx 视为通道错误直接抛出（与 workbuddy2api 口径一致）。
 */
async function fetchCodebuddyTokenOnce(
  provider: CodebuddyOAuthProviderId,
  state: string,
  options?: OAuthFetchOptions,
): Promise<CodebuddyTokenData | null> {
  const { base, origin } = codebuddyRealmConfig(provider)
  const response = await oauthFetch(
    `${base}/v2/plugin/auth/token?state=${encodeURIComponent(state)}`,
    { method: "GET", headers: codebuddyOAuthHeaders(origin) },
    options,
  )
  if (!response.ok) {
    if (response.status >= 500) {
      throw new Error(
        `CodeBuddy OAuth token endpoint error: HTTP ${response.status}`,
      )
    }
    return null
  }
  const body = (await response.json()) as CodebuddyEnvelope
  const data = body.data
  if (body.code !== 0 || !data || typeof data !== "object") {
    return null
  }
  const accessToken = readString(data, "accessToken")
  if (!accessToken) {
    return null
  }
  return {
    accessToken,
    refreshToken: readString(data, "refreshToken"),
    expiresIn: readNumber(data, "expiresIn"),
    domain: readString(data, "domain"),
  }
}

export interface CodebuddyAccountInfo {
  uid: string
  enterpriseId: string
  nickname: string
}

/**
 * 登录账号信息（best-effort：失败不阻断，token 已拿到即可用）。
 */
async function fetchCodebuddyAccount(
  provider: CodebuddyOAuthProviderId,
  state: string,
  accessToken: string,
  options?: OAuthFetchOptions,
): Promise<CodebuddyAccountInfo> {
  const empty = { uid: "", enterpriseId: "", nickname: "" }
  try {
    const { base, origin } = codebuddyRealmConfig(provider)
    const response = await oauthFetch(
      `${base}/v2/plugin/login/account?state=${encodeURIComponent(state)}`,
      {
        method: "GET",
        headers: {
          ...codebuddyOAuthHeaders(origin),
          Authorization: `Bearer ${accessToken}`,
        },
      },
      options,
    )
    const data = await readEnvelopeData(response, "login account")
    return {
      uid: readString(data, "uid"),
      enterpriseId: readString(data, "enterpriseId"),
      nickname: readString(data, "nickname"),
    }
  } catch {
    return empty
  }
}

/**
 * 国内版登录后签到（幂等，best-effort：失败只记日志，不阻断登录）。
 * 对齐 workbuddy2api `login.sh` 的签到分支（国际版跳过）。
 */
async function checkinCodebuddyCn(
  accessToken: string,
  uid: string,
  enterpriseId: string,
  domain: string,
  options?: OAuthFetchOptions,
): Promise<void> {
  try {
    const headers: Record<string, string> = {
      Authorization: `Bearer ${accessToken}`,
      Accept: "application/json",
      "Content-Type": "application/json",
      "X-User-Id": uid,
    }
    if (enterpriseId) {
      headers["X-Enterprise-Id"] = enterpriseId
      headers["X-Tenant-Id"] = enterpriseId
    }
    if (domain) {
      headers["X-Domain"] = domain
    }
    await oauthFetch(
      CODEBUDDY_CHECKIN_URL,
      { method: "POST", headers, body: "{}" },
      options,
    )
  } catch (error: unknown) {
    logger.debug(
      "CodeBuddy CN daily checkin after OAuth login failed (non-blocking):",
      error instanceof Error ? error.message : error,
    )
  }
}

export interface CodebuddyOAuthBundle {
  accessToken: string
  refreshToken?: string
  expiresAt?: number
  domain?: string
  uid?: string
  enterpriseId?: string
  nickname?: string
}

export interface CodebuddyPollOptions extends OAuthFetchOptions {
  intervalMs?: number
  timeoutMs?: number
}

/**
 * 设备流第 2 步：轮询 token 端点直到用户完成浏览器登录，
 * 再拉取账号信息（+ 国内版签到），返回完整 bundle。
 */
export async function pollCodebuddyDeviceAuthorization(
  provider: CodebuddyOAuthProviderId,
  state: string,
  options?: CodebuddyPollOptions,
): Promise<CodebuddyOAuthBundle> {
  const intervalMs = options?.intervalMs ?? DEFAULT_POLL_INTERVAL_MS
  const timeoutMs = options?.timeoutMs ?? DEFAULT_POLL_TIMEOUT_MS
  const deadline = Date.now() + timeoutMs

  while (Date.now() < deadline) {
    if (options?.signal?.aborted) {
      throw new Error("CodeBuddy device authorization cancelled")
    }
    const token = await fetchCodebuddyTokenOnce(provider, state, options)
    if (token) {
      const account = await fetchCodebuddyAccount(
        provider,
        state,
        token.accessToken,
        options,
      )
      if (provider === "codebuddy-cn") {
        await checkinCodebuddyCn(
          token.accessToken,
          account.uid,
          account.enterpriseId,
          token.domain || codebuddyRealmConfig(provider).domain,
          options,
        )
      }
      return {
        accessToken: token.accessToken,
        refreshToken: token.refreshToken || undefined,
        expiresAt:
          token.expiresIn > 0 ? Date.now() + token.expiresIn * 1000 : undefined,
        domain: token.domain || undefined,
        uid: account.uid || undefined,
        enterpriseId: account.enterpriseId || undefined,
        nickname: account.nickname || undefined,
      }
    }
    await new Promise((resolve) => setTimeout(resolve, intervalMs))
  }

  throw new Error(
    "CodeBuddy device authorization timed out. Please complete the browser login and try again.",
  )
}

/**
 * OAuth bundle 落库（connection 原生）：
 * token 走通用 bundle；realm 专属 baseUrl / headers / metadata.provider
 * 在此固化（codebuddy / codebuddy-cn 共用协议，仅靠 protocol 无法区分）。
 */
export function applyCodebuddyOAuthBundle(
  connection: ProviderConnection,
  provider: CodebuddyOAuthProviderId,
  bundle: CodebuddyOAuthBundle,
): void {
  applyOAuthBundleToCredential(connection, bundle, {
    accountId: bundle.uid,
  })

  const { base, domain } = codebuddyRealmConfig(provider)
  connection.baseUrl = `${base}/v2`
  const headers = { ...connection.headers }
  headers["X-Domain"] = bundle.domain || domain
  if (bundle.uid) {
    headers["X-User-Id"] = bundle.uid
  }
  if (bundle.enterpriseId) {
    headers["X-Enterprise-Id"] = bundle.enterpriseId
    headers["X-Tenant-Id"] = bundle.enterpriseId
  }
  connection.headers = headers

  ensureLegacyMetadata(connection).provider = provider

  if (bundle.nickname && isAutoGeneratedOAuthLabel(connection.name, provider)) {
    connection.name = `CodeBuddy-${bundle.nickname}`
  }
}
